function q_dot = orientationQuaternions(q, u,omega)
         omega2 = [0, omega(1), omega(2), omega(3)]';
         q_dot = (1/2)* [q(1),  q(4), -q(3),  q(2);...
                         q(2),  q(3),  q(4), -q(1);...
                         q(3), -q(2),  q(1),  q(4);...
                         q(4), -q(1), -q(2), -q(3)]     *  omega2;
end